# Generated by Django 5.0.1 on 2024-02-02 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                (
                    "shop_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mylist.shoplist",
                    ),
                ),
            ],
        ),
    ]
