# Generated by Django 5.0.1 on 2024-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylist", "0002_shoplistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoplistitem",
            name="purchased",
            field=models.BooleanField(default=False),
        ),
    ]
