# Generated by Django 5.0.1 on 2024-02-21 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylist", "0003_shoplistitem_purchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoplistitem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(limit_value=1)]
            ),
        ),
    ]
