# Generated by Django 5.0.1 on 2024-02-21 10:26

import mylist.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylist", "0004_alter_shoplistitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoplistitem",
            name="quantity",
            field=models.IntegerField(validators=[mylist.models.validate_gt_0]),
        ),
    ]
