name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    

    runs-on: ubuntu-latest
    container: ubuntu:22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    env:
      POSTGRES_HOST: ${{ vars.PG_HOST }}
      POSTGRES_PASSWORD: ${{ vars.PG_PASS }}
      POSTGRES_PORT: ${{ vars.PG_PORT }}
      POSTGRES_USER: ${{ vars.PG_USER }}
      POSTGRES_DATABASE: ${{ vars.PG_DB }}

    services:
        # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        apt -y install curl postgresql-client libpq-dev
        curl -sS https://bootstrap.pypa.io/get-pip.py | python
        pip3.12 install -r requirements.txt
    - name: Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py check        
    - name: Run Tests
      run: |
        python manage.py test
